#!/bin/sh
# Start YajHFC

# The Java command to use
JAVA=java

# Directories to search java in
#  Sun Java is preferred over other versions of Java here (especially GCJ does not work very well for YajHFC...)
JAVADIRS="
/usr/lib/jvm/java-7-sun
/usr/lib/jvm/java-6-sun
/usr/lib/jvm/java-7-openjdk
/usr/lib/jvm/java-6-openjdk
/usr/lib/jvm/java-1.5.0-sun
/usr
"

# Check if we find Java in the directories listed above. 
# If not, just use the java we find in the PATH
for DIR in $JAVADIRS; do
  if [ -x $DIR/bin/java ]; then
    JAVA=$DIR/bin/java
    break
  fi
done

exec $JAVA -jar /usr/share/yajhfc/yajhfc.jar "$@"

