Document: yajhfc
Title: Debian yajhfc Manual
Author: <insert document author here>
Abstract: This manual describes what yajhfc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yajhfc/yajhfc.sgml.gz

Format: postscript
Files: /usr/share/doc/yajhfc/yajhfc.ps.gz

Format: text
Files: /usr/share/doc/yajhfc/yajhfc.text.gz

Format: HTML
Index: /usr/share/doc/yajhfc/html/index.html
Files: /usr/share/doc/yajhfc/html/*.html


